# Generated by Django 4.2.7 on 2023-12-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=100)),
                ('schoollocation', models.CharField(max_length=100)),
                ('schoolprincipal', models.CharField(max_length=100)),
            ],
        ),
    ]
